// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subscriber.proto

package al.assignment.subscriber.grpc;

public final class QuotaServiceProto {
  private QuotaServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Subscriptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Subscriptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProducerStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProducerStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020subscriber.proto\"A\n\rSubscriptions\022\014\n\004h" +
      "ost\030\001 \001(\t\022\014\n\004port\030\002 \001(\t\022\024\n\014subscription\030" +
      "\003 \003(\t\" \n\016ProducerStatus\022\016\n\006status\030\001 \001(\0102" +
      "m\n\nSubscriber\022.\n\tsubscribe\022\016.Subscriptio" +
      "ns\032\017.ProducerStatus\"\000\022/\n\tisHealthy\022\017.Pro" +
      "ducerStatus\032\017.ProducerStatus\"\000B4\n\035al.ass" +
      "ignment.subscriber.grpcB\021QuotaServicePro" +
      "toP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Subscriptions_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Subscriptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Subscriptions_descriptor,
        new java.lang.String[] { "Host", "Port", "Subscription", });
    internal_static_ProducerStatus_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProducerStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProducerStatus_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
