// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consumer.proto

package al.assignment.consumer.grpc;

public interface ConsumerStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ConsumerStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool status = 1;</code>
   * @return The status.
   */
  boolean getStatus();
}
