// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subscriber.proto

package al.assignment.subscriber.grpc;

public interface ProducerStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProducerStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool status = 1;</code>
   * @return The status.
   */
  boolean getStatus();
}
