// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subscriber.proto

package al.assignment.subscriber.grpc;

public final class QuotaServiceProto {
  private QuotaServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Subscriptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Subscriptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProducerStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProducerStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020subscriber.proto\"%\n\rSubscriptions\022\024\n\014s" +
      "ubscription\030\001 \003(\t\" \n\016ProducerStatus\022\016\n\006s" +
      "tatus\030\001 \001(\0102m\n\nSubscriber\022.\n\tsubscribe\022\016" +
      ".Subscriptions\032\017.ProducerStatus\"\000\022/\n\tisH" +
      "ealthy\022\017.ProducerStatus\032\017.ProducerStatus" +
      "\"\000B4\n\035al.assignment.subscriber.grpcB\021Quo" +
      "taServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Subscriptions_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Subscriptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Subscriptions_descriptor,
        new String[] { "Subscription", });
    internal_static_ProducerStatus_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProducerStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProducerStatus_descriptor,
        new String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
