// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subscriber.proto

package al.assignment.subscriber.grpc;

public interface SubscriptionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Subscriptions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string subscription = 1;</code>
   * @return A list containing the subscription.
   */
  java.util.List<String>
      getSubscriptionList();
  /**
   * <code>repeated string subscription = 1;</code>
   * @return The count of subscription.
   */
  int getSubscriptionCount();
  /**
   * <code>repeated string subscription = 1;</code>
   * @param index The index of the element to return.
   * @return The subscription at the given index.
   */
  String getSubscription(int index);
  /**
   * <code>repeated string subscription = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the subscription at the given index.
   */
  com.google.protobuf.ByteString
      getSubscriptionBytes(int index);
}
